---
# Defaults for grafana role

grafana_image: "grafana/grafana:10.4.5"
grafana_network: "monitoring"

grafana_container_name: "grafana"

grafana_volumes_root: "/opt/docker_volumes/grafana"

grafana_data_volume: "grafana_data"
grafana_provisioning_volume: "grafana_provisioning"

# Publish ports - empty to use reverse proxy only
# grafana_published_ports:
#   - "3000:3000"
grafana_published_ports: []

# Admin credentials (use Vault)
grafana_admin_user: "admin"
grafana_admin_password: "admin"

grafana_env:
  GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user }}"
  GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
  GF_USERS_ALLOW_SIGN_UP: "false"

grafana_restart_policy: always
