---
- name: Install Fluent Bit package
  ansible.builtin.package:
    name: "{{ fluentbit_package_name }}"
    state: present
  tags: ['install', 'fluentbit']

- name: Render Fluent Bit config
  ansible.builtin.template:
    src: fluent-bit.conf.j2
    dest: /etc/fluent-bit/fluent-bit.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: Restart fluent-bit
  tags: ['config', 'fluentbit']

- name: Ensure fluent-bit is enabled and running
  ansible.builtin.service:
    name: fluent-bit
    enabled: true
    state: started
  tags: ['service', 'fluentbit']
